### ISSUE TITLE
Is the CNAME threat relevant?  Could you elaborate?

### ISSUE THREAD

**Issue by Zenexer** [sleevi/psl-problems#4]
Regarding the following paragraph:

> In addition to breaking site operators’ expectations, it also breaks browsers’ expectations. The PSL is commonly used to infer organizational boundaries; if there is “sameness” of the domain, it must be “first party” or the same organization, while if it’s a different domain, it must be a different organization, or “third party”. However, these assumptions break down, because there’s no guarantee that login.example.com and logs.example.com are the same entity. If the site operator is presumed malicious and trying to exchange information, it’s trivial for them to configure a CNAME such that logs.example.com points to logging.example, bypassing the normal restrictions that might apply to loading logging.example from login.example.com, because, to the browser, both login.example.com and logs.example.com are operated by example.com.

It’s unclear what threat you’re describing here—it sounds like a mistake, [as I’ve explained on Hacker News](https://news.ycombinator.com/item?id=20908118):

> The only implications of which I’m aware are in relation to web servers that serve the same content regardless of the Host header. It is then possible for someone to log into and interact normally with the website, but the cookies will be associated with the domain controlled by the attacker. The attacker can then change where the domain points later and retrieve the cookies.
This sort of attack is rather obscure, though. It’s a lot more effective to create a phishing site with just a log in form—or, if you want to get fancy, even proxy everything directly from the real website. You can then steal passwords immediately, rather than stealing session cookies after-the-fact. This works even against servers that pay attention to the Host header.
>
> Edit: After re-reading the relevant portion of the article, I believe the author is referring to something similar to this invalid scenario:
>
> 1. Alice operates a web store at alice.example.
> 2. To make purchases, alice.example makes HTTP requests to api.alice.example from within the browser.
>  3. api.alice.example doesn’t pay attention to Host headers.
>  4. Mallory operates a malicious website at mallory.example.
>  5. Mallory cannot make requests to api.alice.example from mallory.example—that would break the same-origin policy. She works around this by configuring api.mallory.example as a CNAME to api.alice.example.
>  6. Bob has an account at alice.example, and is currently logged in.
>  7. Mallory tricks Bob into visiting mallory.example.
>  8. The content loaded by mallory.example makes a request to api.mallory.example indicating that Bob is making a purchase.
>
> This doesn’t work—Bob is safe, and Mallory doesn’t score any loot. When the browser makes the request to api.mallory.example, it will pass cookies from api.mallory.example and mallory.example, not api.alice.example and alice.example. The browser pretends it has no idea that api.mallory.example and api.alice.example point to the same server.
In order for this to work, Bob would need to log in again, but this time at mallory.example—and this brings us back to my original point; it’s easier and more effective to set up a standard phishing page without any CNAME shenanigans.
> 
> While I agree with most of the author’s points, this one baffles me. I don’t see any realistic security implication of what the author has described in this scenario. There are theoretical implications, but in every case it seems there are far easier and more effective attacks. Furthermore, it’s nearly impossible to solve the problem described here; the proposed solutions the author mentions for replacing the Public Suffix List don’t resolve the CNAME threat I’ve described.

**Comment by sleevi** [comment]
I’m afraid you’ve greatly overthought the example, and missed the simpler
one.

When a browser feature is, for privacy reasons, restricted to eTLD+1 on the
basis of “prevent third parties from accessing the data”, it fails to
actually do that, because you can just use CNAMEs to point to the third
party. That is, the first and third party are “colluding” (from the point
of view of the browser) to bypass such restrictions.

To use a common example of intent vs reality, blocking metrics.example from
loading in news.example does nothing if you allow eTLD+1, because they can
just move to metrics.news.example CNAMEd to metrics.example, and it will
load just fine.

It really is nothing more complex than that.

**Comment by Zenexer** [comment]
Thanks for the quick reply!

I’m a little confused as to why that’s relevant. There doesn’t even need to be any collusion or use of CNAMEs to make that possible; one could simply proxy the content. Where does this distinction come into play?

If metrics.news.example wants to serve content that is normally on news.example—whether it be via CNAME, a reverse proxy, or simply copying the content—the browser has no way of stopping that, and it never will, no matter how we eventually replace the PSL.

Currently, cookies aren’t shared between metrics.news.example and metrics.example as long as example is a public suffix.

If the concern isn’t cookies/tokens/etc., but rather content, there is no possible way to prevent the same content from appearing on both hostnames.

**Comment by sleevi** [comment]
You are correct in all of this, and yet still some features are being built
or promoted as assuming only a single logical organization has access to
the data. This logic, in turn, leads to the proxying like you describe.

The point of that, in the context of Web Platform feature proposals, is to
recognize the PSL is by no means a speed bump, and an unnecessary middle
step that provides no value.

**Comment by Zenexer** [comment]
Thanks for the clarification.
